apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: solaoluwalufa/portfolio-website:v2.0
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: db
        - name: DB_NAME
          value: webappdb
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password
      imagePullSecrets:
      - name: myregistry-secret


apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
